### ISSUE TITLE
Unwind breaks deinit

### ISSUE THREAD

**Issue by IanLeatherbury** [felipericieri/FRStretchImageView#2]
[Line 117](https://github.com/felipericieri/FRStretchImageView/blob/master/FRStretchImageView/FRStretchImageView.swift#L117) needs a `?` so that when you unwind to a page it does not throw an exception (the scrollview is already nil due to the way unwind works).

Should be: `self.scrollView?.removeObserver(self, forKeyPath: self.keyPathObserved, context: &self.context)` 

Thanks!

**Comment by felipericieri** [comment]
Thanks so much for this PR @IanLeatherbury, its approved & I will merge it today.

**Comment by IanLeatherbury** [comment]
No prob, thanks for the pod!

**Comment by felipericieri** [comment]
Merged @IanLeatherbury 🚀
